title: Software Engineering Interview Guide
description: A friendly, no-bs place to refresh your brain before hopping into any technical interview
theme: jekyll-theme-cayman
markdown: kramdown
show_downloads: false
